"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from config import AppConfig
APP_CONFIG = AppConfig()

APP = ['main.py']
APP_NAME = f"{APP_CONFIG.name}"
APP_VERSION = f"{APP_CONFIG.version}"
APP_DESCRIPTION = f"{APP_CONFIG.description}"
APP_ID = f"{APP_CONFIG.identifier}"
APP_LICENSE = f"{APP_CONFIG.license}"

DATA_FILES = [
    "resources/meeting.png",
    "resources/watching.png",
    "resources/manual.png",
    "resources/icon.icns",
    "config-default.yaml"
]

OPTIONS = {
    "argv_emulation": False,
    "iconfile": "resources/icon.icns",
    "plist": {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleVersion': APP_VERSION,
        'CFBundleIdentifier': APP_ID,
        'CFBundleGetInfoString': APP_DESCRIPTION,
        'NSHumanReadableCopyright': APP_LICENSE,
        'LSUIElement': True,
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
