"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['meeting_watcher.py']
APP_NAME = "Meeting Watcher"

DATA_FILES = ["in_meeting.png", "watching.png", "icon.icns", "config.yaml"]
OPTIONS = {
    "argv_emulation": True,
    "iconfile": "icon.icns",
    "plist": {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleIdentifier': "com.64byte.osx.meeting_watcher",
        'CFBundleGetInfoString': "Watch for Zoom Meetings and toggle a light",
        'LSUIElement': True,
    }
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
